name: smoketest-code-only
on: [push, pull_request]
jobs:
  cpu-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install deps (CPU)
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.1.2+cpu torchvision==0.16.2+cpu torchaudio==2.1.2+cpu --index-url https://download.pytorch.org/whl/cpu
          pip install gpytorch==1.11 linear_operator==0.5.2
          pip install -r requirements.txt
      - name: Smoketest imports
        run: python tests/smoketest.py
